echo "=============================================="
echo "          PASSWORD STRENGTH CHECKER           "
echo "=============================================="
echo "ABOUT:"
echo "This script evaluates the strength of a given password"
echo "based on the following criteria:"
echo "  1. Length: Minimum of 8 characters."
echo "  2. Composition:"
echo "     - At least one uppercase letter [A-Z]."
echo "     - At least one lowercase letter [a-z]."
echo "     - At least one digit [0-9]."
echo "     - At least one special character [!@#$%^&*(),.?\":{}|<>]."
echo
echo "PURPOSE:"
echo "Helps users create secure passwords by:"
echo "  - Promoting good password practices."
echo "  - Providing feedback on password strength."
echo
echo "OUTPUT:"
echo "The password is categorized as:"
echo "  - Strong: Meets all criteria."
echo "  - Moderate: Missing special characters but otherwise good."
echo "  - Weak: Fails to meet most criteria."
echo
echo "USE CASES:"
echo "  - Personal security checks for stronger passwords."
echo "  - Education on password security in training sessions."
echo "  - Automated systems for password validation."
echo "=============================================="
